services:
  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    volumes:
      - backend_data:/app/data

  frontend:
    build: ./frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://110.40.133.106
    depends_on:
      - backend

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  backend_data:
