services:
  backend:
    build:
      context: ./backend
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
    restart: always
    env_file: ./backend/.env
    volumes:
      - backend_data:/app/data

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://110.40.133.106
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
    restart: always
    depends_on:
      - backend

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  backend_data:
